import { colors, radius, shadows, spacing } from '@/constants/theme';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
const reminders = [
  { title: 'Orvosi időpont', detail: 'Anna · holnap 09:30', icon: 'medical-outline' as const, color: colors.pink },
  { title: 'Gyógyszer bevétele', detail: 'Lili · ma 20:00', icon: 'medkit-outline' as const, color: colors.teal },
  { title: 'Születésnap', detail: 'Máté · 3 nap múlva', icon: 'gift-outline' as const, color: colors.purple },
  { title: 'Biztosítás megújítása', detail: 'Páncélterem · 2 hét múlva', icon: 'shield-checkmark-outline' as const, color: colors.primary },
];
export default function RemindersScreen() { const router = useRouter(); return <SafeAreaView style={styles.safeArea} edges={['top']}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.headerButton}><Ionicons name="chevron-back" size={25} color={colors.textPrimary} /></Pressable><Text style={styles.title}>Emlékeztetők</Text><Ionicons name="calendar-outline" size={22} color={colors.primary} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.summary}><Ionicons name="notifications" size={26} color={colors.primary} /><View style={styles.summaryContent}><Text style={styles.summaryTitle}>Fontos dolgok</Text><Text style={styles.summaryText}>Ne maradjatok le semmiről.</Text></View><Text style={styles.summaryCount}>{reminders.length}</Text></View><Text style={styles.sectionTitle}>Közelgő emlékeztetők</Text>{reminders.map((reminder) => <Pressable key={reminder.title} onPress={() => Alert.alert(reminder.title, 'Az emlékeztető részletei hamarosan szerkeszthetők.')} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={[styles.icon, { backgroundColor: `${reminder.color}18` }]}><Ionicons name={reminder.icon} size={24} color={reminder.color} /></View><View style={styles.cardContent}><Text style={styles.cardTitle}>{reminder.title}</Text><Text style={styles.cardText}>{reminder.detail}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.textMuted} /></Pressable>)}</ScrollView><Pressable onPress={() => Alert.alert('Új emlékeztető', 'Az új emlékeztető létrehozása hamarosan elérhető.')} style={({ pressed }) => [styles.fab, pressed && styles.pressed]}><Ionicons name="add" size={31} color={colors.white} /></Pressable></SafeAreaView>; }
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, header: { minHeight: 64, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.round, backgroundColor: colors.surface }, title: { color: colors.textPrimary, fontSize: 27, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 110, gap: spacing.md }, summary: { padding: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radius.xl, backgroundColor: colors.primarySoft }, summaryContent: { flex: 1, gap: 3 }, summaryTitle: { color: colors.textPrimary, fontSize: 17, fontWeight: '900' }, summaryText: { color: colors.textSecondary, fontSize: 12 }, summaryCount: { color: colors.primary, fontSize: 28, fontWeight: '900' }, sectionTitle: { marginTop: spacing.sm, color: colors.textPrimary, fontSize: 17, fontWeight: '900' }, card: { minHeight: 78, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surface, ...shadows.card }, icon: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: 24 }, cardContent: { flex: 1, gap: 4 }, cardTitle: { color: colors.textPrimary, fontSize: 14, fontWeight: '900' }, cardText: { color: colors.textSecondary, fontSize: 12 }, fab: { position: 'absolute', right: spacing.lg, bottom: spacing.xl, width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderRadius: 29, backgroundColor: colors.primary, ...shadows.floating }, pressed: { opacity: 0.72, transform: [{ scale: 0.97 }] } });
