import { colors, radius, shadows, spacing } from '@/constants/theme';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

function SettingRow({ icon, title, description, right, onPress }: { icon: React.ComponentProps<typeof Ionicons>['name']; title: string; description?: string; right?: React.ReactNode; onPress?: () => void }) {
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name={icon} size={21} color={colors.primary} /></View><View style={styles.rowContent}><Text style={styles.rowTitle}>{title}</Text>{description ? <Text style={styles.rowDescription}>{description}</Text> : null}</View>{right ?? <Ionicons name="chevron-forward" size={18} color={colors.textMuted} />}</Pressable>;
}

export default function SettingsScreen() {
  const router = useRouter();
  const [dark, setDark] = React.useState(false);
  const [largeText, setLargeText] = React.useState(false);
  const [twoFactor, setTwoFactor] = React.useState(false);
  return <SafeAreaView style={styles.safeArea} edges={['top']}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.headerButton}><Ionicons name="chevron-back" size={25} color={colors.textPrimary} /></Pressable><Text style={styles.title}>Beállítások</Text><Ionicons name="settings-outline" size={22} color={colors.primary} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.section}>Megjelenés</Text><View style={styles.card}><SettingRow icon="moon-outline" title="Sötét mód" description="Sötét színséma használata" right={<Switch value={dark} onValueChange={setDark} trackColor={{ false: colors.border, true: colors.primaryLight }} />} /><SettingRow icon="accessibility-outline" title="Akadálymentesség" description="Nagyobb szöveg és kontraszt" right={<Switch value={largeText} onValueChange={setLargeText} trackColor={{ false: colors.border, true: colors.primaryLight }} />} /></View><Text style={styles.section}>Biztonság</Text><View style={styles.card}><SettingRow icon="shield-checkmark-outline" title="Kétlépcsős azonosítás" description={twoFactor ? 'Bekapcsolva' : 'Nincs bekapcsolva'} right={<Switch value={twoFactor} onValueChange={setTwoFactor} trackColor={{ false: colors.border, true: '#9BE5D5' }} thumbColor={twoFactor ? colors.success : undefined} />} /><SettingRow icon="phone-portrait-outline" title="Megbízható eszközök" description="Eszközök kezelése" onPress={() => Alert.alert('Megbízható eszközök', 'Az eszközkezelés hamarosan elérhető.')} /><SettingRow icon="lock-closed-outline" title="Adatvédelem" description="Engedélyek és láthatóság" onPress={() => Alert.alert('Adatvédelem', 'Az adatvédelmi beállítások hamarosan elérhetők.')} /></View><Text style={styles.section}>Alkalmazás</Text><View style={styles.card}><SettingRow icon="notifications-outline" title="Értesítések" description="Értesítési beállítások" onPress={() => router.push('/notifications')} /><SettingRow icon="language-outline" title="Nyelv" description="Magyar" onPress={() => Alert.alert('Nyelv', 'Jelenleg csak a magyar nyelv érhető el.')} /></View><View style={styles.version}><Text style={styles.versionText}>FamilyHub · 1.0.0</Text></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: colors.background }, header: { minHeight: 64, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.round, backgroundColor: colors.surface }, title: { color: colors.textPrimary, fontSize: 27, fontWeight: '900' }, content: { padding: spacing.lg, paddingBottom: 36, gap: spacing.md }, section: { marginTop: spacing.sm, color: colors.textMuted, fontSize: 11, fontWeight: '900', letterSpacing: 0.7, textTransform: 'uppercase' }, card: { borderRadius: radius.xl, backgroundColor: colors.surface, ...shadows.card }, row: { minHeight: 70, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, rowIcon: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', borderRadius: 21, backgroundColor: colors.primarySoft }, rowContent: { flex: 1, gap: 3 }, rowTitle: { color: colors.textPrimary, fontSize: 13, fontWeight: '900' }, rowDescription: { color: colors.textMuted, fontSize: 11 }, version: { alignItems: 'center', padding: spacing.lg }, versionText: { color: colors.textMuted, fontSize: 11 }, pressed: { opacity: 0.72 } });
